### ISSUE TITLE
smol example consumes significant CPU while idle

### ISSUE THREAD

**Issue by mayfieldiv** [stjepang/minihttp#1]
Only tested on Windows 10

`cargo run --release --example smol` causes CPU usage to jump to ~22% on an 8-core processor

Running the other examples result in no idle CPU usage

**Comment by stjepang** [comment]
Is it stable, does it stay at around 22% the whole time?

**Comment by stjepang** [comment]
It would be interesting to see what happens if we add a println at this line:

https://github.com/stjepang/smol/blob/e48a8787f4e32a5b04f2cfb659639bb7edad3066/src/run.rs#L143

I wonder if one worker thread keeps spinning for some reason...

**Comment by mayfieldiv** [comment]
It's pretty stable at 22% ± 1%

I just made sure everything was up-to-date.. still happening

I added the println locally where you said and it's getting hit constantly

**Comment by stjepang** [comment]
This is now fixed in smol v0.1.10.
